# Generated by Django 6.0.3 on 2026-04-01 11:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('eligibilite_garde_nuit', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='RegleLegale',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('valeur_numerique', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'regle_legale',
            },
        ),
        migrations.CreateModel(
            name='TypeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('impacte_quota_garde', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'type_absence',
            },
        ),
        migrations.CreateModel(
            name='TypeGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('is_nuit', models.BooleanField(default=False)),
                ('is_astreinte', models.BooleanField(default=False)),
                ('duree_standard_heures', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'type_garde',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('prerequis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_suivantes', to='api.certification')),
            ],
            options={
                'db_table': 'certification',
            },
        ),
        migrations.CreateModel(
            name='Soignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_actif', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.grade')),
            ],
            options={
                'db_table': 'soignant',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('capacite_lits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('niveau_criticite', models.IntegerField(default=1)),
                ('soignant_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_geres', to='api.soignant')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('pourcentage_tps_travail', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('heures_max_hebdo', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('soignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='api.soignant')),
            ],
            options={
                'db_table': 'contrat',
            },
        ),
        migrations.CreateModel(
            name='SoignantCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateField()),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certification')),
                ('soignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='api.soignant')),
            ],
            options={
                'db_table': 'soignant_certification',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_specialites', to='api.specialite')),
            ],
            options={
                'db_table': 'specialite',
            },
        ),
        migrations.AddField(
            model_name='soignant',
            name='specialites',
            field=models.ManyToManyField(blank=True, db_table='soignant_specialite', to='api.specialite'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('soignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='api.soignant')),
                ('type_absence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.typeabsence')),
            ],
            options={
                'db_table': 'absence',
            },
        ),
        migrations.CreateModel(
            name='UniteSoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='api.service')),
            ],
            options={
                'db_table': 'unite_soin',
            },
        ),
        migrations.CreateModel(
            name='PosteGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_prevu', models.DateTimeField()),
                ('fin_prevue', models.DateTimeField()),
                ('nb_soignants_min', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('nb_soignants_max', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('certifications_requises', models.ManyToManyField(blank=True, db_table='poste_certification_requise', to='api.certification')),
                ('type_garde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.typegarde')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='api.unitesoin')),
            ],
            options={
                'db_table': 'poste_garde',
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('VALIDE', 'Valide'), ('ANNULE', 'Annulé')], default='VALIDE', max_length=20)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='api.postegarde')),
                ('soignant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='affectations', to='api.soignant')),
            ],
            options={
                'db_table': 'affectation',
                'unique_together': {('poste', 'soignant')},
            },
        ),
    ]
