# Generated by Django 6.0.3 on 2026-04-01 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('impacts_quota', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'absence_type',
            },
        ),
        migrations.CreateModel(
            name='CareUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'care_unit',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_hours_per_week', models.IntegerField(blank=True, null=True)),
                ('leave_days_per_year', models.IntegerField(blank=True, null=True)),
                ('night_shift_allowed', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'contract_type',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_type', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bed_capacity', models.IntegerField()),
                ('criticality_level', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration_hours', models.IntegerField()),
                ('requires_rest_after', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shift_type',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dependencies', models.ManyToManyField(db_table='certification_dependency', related_name='required_by', to='api.certification')),
            ],
            options={
                'db_table': 'certification',
            },
        ),
        migrations.CreateModel(
            name='PatientLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('patient_count', models.IntegerField()),
                ('occupancy_rate', models.FloatField(blank=True, null=True)),
                ('care_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_loads', to='api.careunit')),
            ],
            options={
                'db_table': 'patient_load',
            },
        ),
        migrations.AddField(
            model_name='careunit',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_units', to='api.service'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('min_staff', models.IntegerField(default=1)),
                ('max_staff', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('care_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.careunit')),
                ('required_certifications', models.ManyToManyField(blank=True, db_table='shift_required_certification', to='api.certification')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shifttype')),
            ],
            options={
                'db_table': 'shift',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.specialty')),
                ('staff', models.ManyToManyField(db_table='staff_specialty', related_name='specialties', to='api.staff')),
            ],
            options={
                'db_table': 'specialty',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignments', to='api.shift')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shift_assignments', to='api.staff')),
            ],
            options={
                'db_table': 'shift_assignment',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_services', to='api.staff'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('staff', models.ManyToManyField(db_table='staff_role', related_name='roles', to='api.staff')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_hard_constraint', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='api.staff')),
            ],
            options={
                'db_table': 'preference',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('is_planned', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('absence_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.absencetype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='api.staff')),
            ],
            options={
                'db_table': 'absence',
            },
        ),
        migrations.CreateModel(
            name='StaffCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certification')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='api.staff')),
            ],
            options={
                'db_table': 'staff_certification',
            },
        ),
        migrations.CreateModel(
            name='StaffLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('from_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='api.staff')),
                ('to_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.service')),
            ],
            options={
                'db_table': 'staff_loan',
            },
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='api.service')),
            ],
            options={
                'db_table': 'service_status',
                'indexes': [models.Index(condition=models.Q(('end_date__isnull', True)), fields=['service'], name='idx_active_service_status')],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('workload_percent', models.IntegerField(default=100)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contracttype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.staff')),
            ],
            options={
                'db_table': 'contract',
                'indexes': [models.Index(condition=models.Q(('end_date__isnull', True)), fields=['staff'], name='idx_active_contract')],
            },
        ),
        migrations.CreateModel(
            name='StaffServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='api.staff')),
            ],
            options={
                'db_table': 'staff_service_assignment',
                'indexes': [models.Index(condition=models.Q(('end_date__isnull', True)), fields=['staff'], name='idx_active_service_assig')],
            },
        ),
    ]
